export interface Estudiante{
    tCodEstudiante?: string;
    tCodGrado?: string;
    tCodSeccion?: string;
    tCodTipoDocumento?: string;
    lValidadoRenic?: boolean;
    tCodSiagieEst?: string;
    tAPaterno?: string;
    tAMaterno?: string;
    tNombres?: string;
    tSexo?: string;
    fNacimiento?: Date;
    nEdad?: Number;
    tEstadoMatricula?: string;
    tNroDocumento?: string;
    fRegistro?: Date;
    lActivo?: string;
    tCodSeguro?: string;
    tCodDistrito?: string;
    tDireccion?: string;
    tTelefono?: string;
    tEmail?: string;
    lDiscapacidad?: boolean;
    tDiscapacidadObs?: string;
    lExonaradoR?: boolean;
    lCierre?: boolean; 
    tDetTipoDoc ?: string;
    tDetEstadoMa? : string;
    tDetGrado?: string;
    tEstadoRegistro? : string;
    tDetEstadoRegistro? : string;
    tNivel?: string;
    tDetNivel?: string;
    tApellidosNombres? : string;
    tDetSexo?: string;
    lRatificacion?: boolean;
    tVive?: string;
    tApoderado?:string;
    lHermanos?: boolean;
    nCantHermanos?: number;

    tNroDocumentoRepre?: number;
    tAPaternoRepre?: string;
    tAMaternoRepre?: string;
    tNombresRepre?: string;
    tTipoDocumentoRepre?: string;
    tParentescoRepre?: string;
    tDireccionRepre?: string;
    tTelefonoRepre?: string;
    tEmailRepre?: string;
    tCodParentescoRepre?: string;
}